export const products = [
  {
    id: 1,
    name: "Nasi Goreng",
    slug: "nasi-goreng",
    price: 15000,
    stock: 10,
    category: 1,
    category_name: "Makanan",
    rating: 4.5,
    img: "/images/nasi-goreng.jpeg",
  },
  {
    id: 2,
    name: "Ayam Geprek",
    slug: "ayam-geprek",
    price: 18000,
    stock: 8,
    category: 1,
    category_name: "Makanan",
    rating: 4.7,
    img: "/images/ayam-geprek.jpeg",
  },
  {
    id: 3,
    name: "Mie Goreng",
    slug: "mie-goreng",
    price: 13000,
    stock: 12,
    category: 1,
    category_name: "Makanan",
    rating: 4.3,
    img: "/images/mie-goreng.jpeg",
  },
  {
    id: 4,
    name: "Es Teh",
    slug: "es-teh",
    price: 5000,
    stock: 20,
    category: 2,
    category_name: "Minuman",
    rating: 4.4,
    img: "/images/es-teh.jpeg",
  },
  {
    id: 5,
    name: "Es Jeruk",
    slug: "es-jeruk",
    price: 7000,
    stock: 15,
    category: 2,
    category_name: "Minuman",
    rating: 4.6,
    img: "/images/es-jeruk.jpeg",
  },
  {
    id: 6,
    name: "Kopi Susu",
    slug: "kopi-susu",
    price: 10000,
    stock: 10,
    category: 2,
    category_name: "Minuman",
    rating: 4.8,
    img: "/images/kopi-susu.jpeg",
  },
];